---
- hosts: localhost
  sudo: yes
  vars:
    http_port: 80
    domain: example.com
  tasks:

    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: create lb config file
      file:
        path: "/etc/apache2/conf.d/lb.conf"
        state: touch

    - name: apache2 proxy enable as LB
      blockinfile: dest=/etc/apache2/conf.d/lb.conf
      block: |
        <VirtualHost: 80>
        <Proxy balancer://tomcat>
          BalancerMember "http://localhost:8080" route=1
          BalancerMember "http://localhost:8081" route=2
	  ProxySet stickysession=ROUTEID
        </Proxy>
        <Location /balancer-manager>
          SetHandler balancer-manager
        <Location>
        ProxyPass /balancer-manager
        ProxyPass        / "balancer://tomcat"
        ProxyPassReverse / "balancer://tomcat"

      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted